name: OIDC Test

on:
  workflow_dispatch: # allows manual trigger

permissions:
  id-token: write  # required for OIDC
  contents: read

jobs:
  test-oidc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        id: aws_creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::306442480424:role/e2esa-aws-terraform-github-oidc
          aws-region: us-east-1

      - name: Show caller identity
        run: aws sts get-caller-identity

      - name: Print AWS temporary credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
          echo "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}"
          echo ""
          echo "🔑 To use from CLI, run:"
          echo "export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
          echo "export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
          echo "export AWS_SESSION_TOKEN='${AWS_SESSION_TOKEN}'"
